=== ensoelectric/x_validation/transform/xsd2html2xml-3.3/examples/complex-sample/complex-sample.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="nestedString">
		<xs:restriction base="xs:string">
			<xs:enumeration value="nestedString Option 1"/>
			<xs:enumeration value="nestedString Option 2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nestedByte">
		<xs:restriction base="xs:byte">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="doubleNestedByte">
		<xs:restriction base="nestedByte">
			<xs:maxInclusive value="10" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="rootElement">
		<xs:annotation>
			<xs:documentation>Root Element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="simpleTypes">
					<xs:annotation>
						<xs:documentation>Simple xs:* types with default restrictions:</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="string" />
							<xs:element name="multiline-string" default="multiline sample">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value=".*(\n)?.*"></xs:pattern>
										<xs:whiteSpace value="collapse" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:byte" name="byte">
								<xs:annotation>
									<xs:documentation>byte (-128 to 127)</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element type="xs:short" name="short" />
							<xs:element type="xs:int" name="int" />
							<xs:element type="xs:long" name="long" />
							<xs:element type="xs:decimal" name="decimal" />
							<xs:element type="xs:float" name="float" />
							<xs:element type="xs:double" name="double" />
							<xs:element type="xs:boolean" name="boolean" />
							<xs:element type="xs:date" name="date" />
							<xs:element type="xs:time" name="time" />
							<xs:element type="xs:dateTime" name="dateTime" />
							<xs:element type="xs:anyURI" name="anyURI" />
							<xs:element type="xs:hexBinary" name="hexBinary" />
							<xs:element type="xs:base64Binary" name="base64Binary" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dates">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:date" name="date" />
							<xs:element type="xs:time" name="time" />
							<xs:element type="xs:dateTime" name="dateTime" />
							<xs:element type="xs:gDay" name="gDay" />
							<xs:element type="xs:gMonth" name="gMonth" />
							<xs:element name="gMonthEnum">
								<xs:annotation>
									<xs:documentation>gMonth as enumeration</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:gMonth">
										<xs:enumeration value="--01">
											<xs:annotation>
												<xs:documentation>January</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="--02">
											<xs:annotation>
												<xs:documentation>February</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="--03">
											<xs:annotation>
												<xs:documentation>March</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:gMonthDay" name="gMonthDay"/>
							<xs:element type="xs:gYear" name="gYear"/>
							<xs:element type="xs:gYearMonth" name="gYearMonth"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="durations">
					<xs:annotation>
						<xs:documentation>Various durations:</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dateDuration">
								<xs:simpleType>
									<xs:restriction base="xs:duration">
										<xs:pattern value="P\d{1,3}D" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="timeDuration">
								<xs:simpleType>
									<xs:restriction base="xs:duration">
										<xs:pattern value="PT\d{1,2}M" />
										<xs:minInclusive value="PT1M" />
										<xs:maxInclusive value="PT10M" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="defaults">
					<xs:annotation>
						<xs:documentation>Simple elements with default and fixed values:</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="defaultString" default="this is the default value" />
							<xs:element type="xs:string" name="fixedString" fixed="this is a fixed value" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="positiveIntegers">
					<xs:annotation>
						<xs:documentation>Integers that all allow only positive values:</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:positiveInteger" name="positiveInteger" />
							<xs:element type="xs:nonNegativeInteger" name="negativeInteger" />
							<xs:element type="xs:unsignedInt" name="unsignedInt" />
							<xs:element name="integer">
								<xs:annotation>
									<xs:documentation>integer with min restriction</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="0" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="restrictions">
					<xs:annotation>
						<xs:documentation>Simple type with enumerations:</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="enumeration">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Option 1" />
										<xs:enumeration value="Option 2">
											<xs:annotation>
												<xs:documentation>Custom labeled option 2</xs:documentation>
											</xs:annotation>
										</xs:enumeration>
										<xs:enumeration value="Option 3" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="fixed-enumeration" fixed="Option 3">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Option 1" />
										<xs:enumeration value="Option 2" />
										<xs:enumeration value="Option 3" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="extensions">
					<xs:annotation>
						<xs:documentation>Various nested (and double nested) extensions:</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element type="nestedString" name="nestedString">
								<xs:annotation>
									<xs:documentation>nestedString-type determines the enumaration values</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element type="nestedByte" name="nestedByte">
								<xs:annotation>
									<xs:documentation>nestedByte-type restricts the byte to min=0</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element type="doubleNestedByte" name="doubleNestedByte">
								<xs:annotation>
									<xs:documentation>doubleNestedByte-type restricts nestedByte to max=10</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element type="xs:string" name="occurrencesSimple" minOccurs="1" maxOccurs="3">
					<xs:annotation>
						<xs:documentation>Recurring simple</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="occurrencesComplex" minOccurs="1" maxOccurs="3">
					<xs:annotation>
						<xs:documentation>Recurring complex</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="child">
								<xs:complexType>
									<xs:attribute type="xs:byte" name="attribute" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="complexSimpleContent">
					<xs:annotation>
						<xs:documentation>Complex element with simple content</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="attribute" use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="choice">
					<xs:annotation>
						<xs:documentation>Element with xs:choice:</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice>
							<xs:element type="xs:byte" name="byte" />
							<xs:element type="xs:short" name="short" />
							<xs:element type="xs:long" name="long" />
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ensoelectric/x_validation/transform/xsd2html2xml-3.3/examples/complex-sample/complex-sample.xml
<?xml version="1.0"?>
<rootElement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="complex-sample.xsd">
	<simpleTypes>
		<string>abcdefghijklmnopqr</string>
		<multiline-string>hello world</multiline-string>
		<byte>1</byte>
		<short>2</short>
		<int>3</int>
		<long>0</long>
		<decimal>0.5</decimal>
		<float>1.1</float>
		<double>2.2</double>
		<boolean>true</boolean>
		<date>2017-03-14</date>
		<time>02:02:00</time>
		<dateTime>2017-03-14T14:02:03</dateTime>
		<anyURI>http://www.github.com</anyURI>
		<hexBinary>76657273696F6E3D312E31310D0A6465736372697074696F6E3D76312E313120666978657320736F6D65206E616D657370616365732069737375657320696E20584D4C206F75747075742E0D0A73697A653D31340D0A75726C2E36343D68747470733A2F2F7777772E6D69636869656C6D65756C656E64696A6B2E6E6C2F77702D636F6E74656E742F75706C6F6164732F786D6C7366672D7570646174652D76312E31312D36342E6578650D0A75726C2E33323D68747470733A2F2F7777772E6D69636869656C6D65756C656E64696A6B2E6E6C2F77702D636F6E74656E742F75706C6F6164732F786D6C7366672D7570646174652D76312E31312D33322E657865</hexBinary>
		<base64Binary>dmVyc2lvbj0xLjExDQpkZXNjcmlwdGlvbj12MS4xMSBmaXhlcyBzb21lIG5hbWVzcGFjZXMgaXNzdWVzIGluIFhNTCBvdXRwdXQuDQpzaXplPTE0DQp1cmwuNjQ9aHR0cHM6Ly93d3cubWljaGllbG1ldWxlbmRpamsubmwvd3AtY29udGVudC91cGxvYWRzL3htbHNmZy11cGRhdGUtdjEuMTEtNjQuZXhlDQp1cmwuMzI9aHR0cHM6Ly93d3cubWljaGllbG1ldWxlbmRpamsubmwvd3AtY29udGVudC91cGxvYWRzL3htbHNmZy11cGRhdGUtdjEuMTEtMzIuZXhl</base64Binary>
	</simpleTypes>
	<dates>
		<date>2017-04-03</date>
		<time>02:03:04</time>
		<dateTime>2017-04-03T14:03:04</dateTime>
		<gDay>---30</gDay>
		<gMonth>--02</gMonth>
		<gMonthEnum>--02</gMonthEnum>
		<gMonthDay>--04-05</gMonthDay>
		<gYear>2017</gYear>
		<gYearMonth>2017-04</gYearMonth>
	</dates>
	<durations>
		<dateDuration>P0D</dateDuration>
		<timeDuration>PT5M</timeDuration>
	</durations>
	<defaults>
		<defaultString>this is no longer the default value</defaultString>
		<fixedString>this is a fixed value</fixedString>
	</defaults>
	<positiveIntegers>
		<positiveInteger>10</positiveInteger>
		<negativeInteger>10</negativeInteger>
		<unsignedInt>10</unsignedInt>
		<integer>10</integer>
	</positiveIntegers>
	<restrictions>
		<enumeration>Option 2</enumeration>
		<fixed-enumeration>Option 3</fixed-enumeration>
	</restrictions>
	<extensions>
		<nestedString>nestedString Option 2</nestedString>
		<nestedByte>0</nestedByte>
		<doubleNestedByte>10</doubleNestedByte>
	</extensions>
	<occurrencesSimple>a</occurrencesSimple>
	<occurrencesComplex>
		<child attribute="1"/>
	</occurrencesComplex>
	<occurrencesComplex>
		<child attribute="2"/>
	</occurrencesComplex>
	<occurrencesComplex>
		<child attribute="3"/>
	</occurrencesComplex>
	<complexSimpleContent attribute="attribute">simple content</complexSimpleContent>
	<choice>
		<byte>1</byte>
	</choice>
</rootElement>
